apiVersion: v1
kind: ConfigMap
metadata:
  name: sag-pp-ismsr-license-config
  namespace: nsp-sag-pp
data:
  msr-licensekey.xml: |
   <?xml version="1.0" encoding="US-ASCII"?>
   <SoftwareAG_License>
   <Component Id="SalesInfo">
   <SerialNumber>0000497888</SerialNumber>
   <LicenseKey>68D56FFE95C8E4FEA38EFAEB2AEC97CE</LicenseKey>
   <CustomerID>3150000</CustomerID>
   <CustomerName>Software AG for Solution Book Internal USE ONLY</CustomerName>
   <ContractDetails>SOFTWARE AG internal license solely for sales promotion and internal training purposes. Please note that this access key is for your personal use only. Access and software shall not be forwarded to anybody else</ContractDetails>
   <ContractPosNumber>10</ContractPosNumber>
   <LicenseTypeDetails>Internal</LicenseTypeDetails>
   <AutoCallHome>No</AutoCallHome>
   </Component>
   <Component Id="ProductInfo">
   <ExpirationDate>2023/10/31</ExpirationDate>
   <OS>win, SunOS, Linux, Linux S390, AIX, HP-UX, MacOS</OS>
   <ProductCode>MSC</ProductCode>
   <ProductID/>
   <ProductName>webMethods Microservices Runtime</ProductName>
   <ProductVersion>10.0</ProductVersion>
   <Usage/>
   <RenewalDate/>
   <HigherLevPosNr/>
   <HigherLevProdCode/>
   <HigherLevProdName/>
   </Component>
   <Component Id="Integration Server">
   <ProductCode>PIE</ProductCode>
   <ProductVersion>10.0</ProductVersion>
   <ConcurrentSessions>Unlimited</ConcurrentSessions>
   <Clustering>yes</Clustering>
   <PubSub>yes</PubSub>
   <ART>yes</ART>
   <RemoteInvoke>yes</RemoteInvoke>
   <GuaranteedDelivery>yes</GuaranteedDelivery>
   <SecurityAuditing>yes</SecurityAuditing>
   <DistributedCache>yes</DistributedCache>
   <EnterpriseGateway>no</EnterpriseGateway>
   <Microservices>yes</Microservices>
   </Component>
   <Component Id="Trading Networks">
   <ProductCode/>
   <MaxPartners/>
   </Component>
   <Component Id="LicenseInfo">
   <PriceUnit>CoreD</PriceUnit>
   <PriceQuantity>16</PriceQuantity>
   <TypeOfInstallation/>
   <LicenseType/>
   <ExtendedRights/>
   <LicenseVersion>1.2</LicenseVersion>
   <Metering>MNO</Metering>
   </Component>
   </SoftwareAG_License>