---
apiVersion: v1
kind: Service
metadata:
  name: sag-pp-msr-svc-nodeport
  labels:
    app: sag-pp-msr-svc-nodeport
  namespace: nsp-sag-pp
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: sag-pp-msr
  ports:
    - name: is-port
      port: 5555
      targetPort: 5555
      nodePort: 30011
    - name: comm-port
      port: 5543
      targetPort: 5543
      nodePort: 30012
    - name: diagnostic-port
      port: 9999
      targetPort: 9999
      nodePort: 30013

---
apiVersion: v1
kind: Service
metadata:
  name: sag-pp-msr-svc-clusterip
  labels:
    app: sag-pp-msr-svc-clusterip
  namespace: nsp-sag-pp
spec:
  type: ClusterIP
  ports:
    - name: is-port
      port: 5555
    - name: comm-port
      port: 5543
    - name: diagnostic-port
      port: 9999
  selector:
    app: sag-pp-msr
