apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sag-pp-um-pvc
  namespace: nsp-sag-pp  
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
