apiVersion: v1
kind: Service
metadata:
  name: sag-pp-um-svc
  labels:
    app: sag-pp-um-svc
  namespace: nsp-sag-pp
spec:
  type: ClusterIP
  ports:
  - name: um-port
    port: 9000
  selector:
    app: sag-pp-um-deploy

---
apiVersion: v1
kind: Service
metadata:
  name: sag-pp-um-svc-nodeport
  labels:
    app: sag-pp-um-svc-nodeport
  namespace: nsp-sag-pp
spec:
  type: NodePort
  selector:
    app: sag-pp-um-deploy
  sessionAffinity: ClientIP
  ports:
  - name: um-port
    port: 9000
    targetPort: 9000
    nodePort: 30021