apiVersion: v1
kind: Service
metadata:
  name: sag-pp-es-svc-h
  labels:
    app: sag-pp-es-svc-h
  namespace: nsp-sag-pp
spec:
  selector:
    app: sag-pp-es-cluster
  clusterIP: None
  ports:
  - port: 9200
    name: server
  - port: 9300
    name: replication
