---
apiVersion: v1
kind: Service
metadata:
  name: sag-pp-es-svc-nodeport
  labels:
    app: sag-pp-es-svc-nodeport
  namespace: nsp-sag-pp
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: sag-pp-es-cluster
  ports:
    - name: es-port
      port: 9200
      targetPort: 9200
      nodePort: 30020