apiVersion: v1
kind: Service
metadata:
  name: sag-pp-kibana-svc-nodeport
  namespace: nsp-sag-pp
  labels:
    component: kibana
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: kibana
  ports:
  - name: http
    port: 5601
    targetPort: 5601
    nodePort: 30022
    protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: sag-pp-kibana-svc
  namespace: nsp-sag-pp
  labels:
    component: kibana
spec:
  selector:
    app: kibana
  ports:
  - name: http
    port: 5601
    targetPort: 5601
    protocol: TCP