apiVersion: v1
kind: ConfigMap
metadata:
  name: sag-pp-kibana-config
  namespace: nsp-sag-pp
data:
  kibana.yml: |
    server.port: 5601
    server.host: "0.0.0.0"
    server.basePath: "/apigatewayui/dashboardproxy"
    elasticsearch.hosts: "http://sag-pp-es-svc-h.nsp-sag-pp.svc.cluster.local:9200"
    kibana.index: "gateway_default_dashboard"
    elasticsearch.requestTimeout: 90000
    pid.file: kibana.pid
    console.enabled: false
    telemetry.enabled: false