---
apiVersion: v1
kind: Service
metadata:
  name: sag-pp-apigw-svc-nodeport
  labels:
    app: sag-pp-apigw-svc-nodeport
  namespace: nsp-sag-pp
spec:
  type: NodePort
  selector:
    app: sag-pp-apigw-cluster
  sessionAffinity: ClientIP
  ports:
    - name: is-port
      port: 5555
      targetPort: 5555
      nodePort: 30007
    - name: comm-port
      port: 5543
      targetPort: 5543
      nodePort: 30008
    - name: apigw-port
      port: 9072
      targetPort: 9072
      nodePort: 30006
    - name: diagnostic-port
      port: 9999
      targetPort: 9999
      nodePort: 30009
---
apiVersion: v1
kind: Service
metadata:
  name: sag-pp-apigw-svc-clusterip
  labels:
    app: sag-pp-apigw-svc-clusterip
  namespace: nsp-sag-pp
spec:
  type: ClusterIP
  ports:
    - name: apigw-port
      port: 9072
    - name: is-port
      port: 5555
    - name: comm-port
      port: 5543
    - name: diagnostic-port
      port: 9999
  selector:
    app: sag-pp-apigw-cluster
